//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grant2FW.DataBaseModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApartmentsCopy
    {
        public int Id { get; set; }
        public string Address { get; set; }
        public Nullable<decimal> Area { get; set; }
        public Nullable<int> NumberOfRooms { get; set; }
        public Nullable<int> Section { get; set; }
        public Nullable<int> Floor { get; set; }
        public Nullable<int> IdStatus { get; set; }
        public Nullable<int> IdApartment { get; set; }
        public Nullable<bool> IsActual { get; set; }
        public Nullable<int> Expenses_Building_An_Apartment { get; set; }
        public Nullable<int> Added_value { get; set; }
    
        public virtual StatusesAppartment StatusesAppartment { get; set; }
        public virtual Appartments Appartments { get; set; }
    }
}
