//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grant2FW.DataBaseModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appartments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Appartments()
        {
            this.ApartmentsCopy = new HashSet<ApartmentsCopy>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdHouse { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApartmentsCopy> ApartmentsCopy { get; set; }
        public virtual Housing Housing { get; set; }
    }
}
