//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grant2FW.DataBaseModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class HousingCopies
    {
        public int Id { get; set; }
        public Nullable<int> OriginalHousingId { get; set; }
        public string Number_House { get; set; }
        public Nullable<int> Cost_House_Construction { get; set; }
        public Nullable<int> Additional_Cost_Apartament_House { get; set; }
        public Nullable<int> Added_Value { get; set; }
        public Nullable<int> Building_Costs { get; set; }
        public Nullable<bool> IsActual { get; set; }
    
        public virtual Housing Housing { get; set; }
    }
}
