//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grant2FW.DataBaseModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class grant_2Entities1 : DbContext
    {
        public grant_2Entities1()
            : base("name=grant_2Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Housing> Housing { get; set; }
        public virtual DbSet<HousingComplex> HousingComplex { get; set; }
        public virtual DbSet<HousingCopies> HousingCopies { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<HousingComplexCopies> HousingComplexCopies { get; set; }
    }
}
