//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grant2FW.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Housing
    {
        public int Id { get; set; }
        public string Street { get; set; }
        public string Number_House { get; set; }
        public Nullable<int> Cost_House_Construction { get; set; }
        public Nullable<int> Additional_Cost_Apartament_House { get; set; }
        public Nullable<int> Id_Housing_Complex { get; set; }
        public string City { get; set; }
        public Nullable<int> Added_Value { get; set; }
        public Nullable<int> Building_Costs { get; set; }
    
        public virtual HousingComplex HousingComplex { get; set; }
    }
}
